name: ConcealConnect
options:
  bundleIdPrefix: com.Conceal
  deploymentTarget:
    iOS: "18.2"

targets:
  ConcealConnect:
    type: application
    platform: iOS
    sources: [App]
    resources: [App/Resources]
    info:
      path: App/Resources/Info.plist

  PacketTunnel:
    type: system-extension
    platform: iOS
    sources: [Extensions/PacketTunnel]
    resources: [Extensions/PacketTunnel/Resources]
    info:
      path: Extensions/PacketTunnel/Resources/Info.plist
    entitlements:
      path: Extensions/PacketTunnel/PacketTunnel.entitlements
