name: ConcealConnect
options:
  bundleIdPrefix: com.Conceal
  deploymentTarget:
    iOS: "18.2"

targets:
  TunnelCore:
    type: framework
    platform: iOS
    sources: [TunnelCore]              # Swift wrapper, C headers
    headers: [TunnelCore/include]
    linkLibraries:
      - path: TunnelCore/lib/libquiche-universal.a
  ConcealConnect:
    type: application
    platform: iOS
    sources: [App]
    resources: [App/Resources]
    info:
      path: App/Resources/Info.plist

  PacketTunnel:
    type: system-extension
    platform: iOS
    sources: [Extensions/PacketTunnel]
    resources: [Extensions/PacketTunnel/Resources]
    info:
      path: Extensions/PacketTunnel/Resources/Info.plist
    entitlements:
      path: Extensions/PacketTunnel/PacketTunnel.entitlements
